<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\Category;

class TestProductSeeder extends Seeder
{
    public function run(): void
    {
        $categories = [
            ['name' => 'ستائر قماشية', 'slug' => 'curtains-fabric'],
            ['name' => 'كنب وأرائك', 'slug' => 'sofas-chairs'],
            ['name' => 'طاولات', 'slug' => 'tables'],
        ];

        foreach ($categories as $categoryData) {
            Category::firstOrCreate(
                ['slug' => $categoryData['slug']],
                [
                    'name' => $categoryData['name'],
                    'description' => 'وصف للفئة',
                    'color' => '#F0F7FF',
                    'sort_order' => 1,
                    'status' => 'active'
                ]
            );
        }

        $categories = Category::all();

        $products = [
            [
                'name' => 'ستائر رولر كلاسيكية',
                'brand' => 'Antartica',
                'collection' => 'Paragon I',
                'description' => 'ستائر رولر عالية الجودة للحماية من أشعة الشمس',
                'price' => 825.00,
                'discount' => 35,
                'image' => '/images/curtain.png',
                'images' => ['/images/curtain.png', '/images/curtain1.png'],
                'rating' => 4,
                'tab' => 'featured',
                'category_id' => $categories->where('name', 'ستائر قماشية')->first()->id,
                'colors' => ['#FFA500', '#87CEEB', '#DDA0DD'],
                'status' => 'active',
                'stock' => 50,
                'sku' => '6-52CH',
                'featured' => true,
                'is_offer' => true,
                'is_bestseller' => false,
                'sales_count' => 15,
                'published_at' => now()->subDays(5),
            ],
            [
                'name' => 'كنبة فاخرة 3 مقاعد',
                'brand' => 'Modern Style',
                'collection' => 'Luxury Series',
                'description' => 'كنبة فاخرة بتصميم عصري ومريح',
                'price' => 1249.00,
                'discount' => 25,
                'image' => '/images/sofa3.png',
                'images' => ['/images/sofa3.png', '/images/sofa.png'],
                'rating' => 5,
                'tab' => 'bestsellers',
                'category_id' => $categories->where('name', 'كنب وأرائك')->first()->id,
                'colors' => ['#8B4513', '#654321', '#A0522D'],
                'status' => 'active',
                'stock' => 30,
                'sku' => 'SOFA-3S',
                'featured' => true,
                'is_offer' => false,
                'is_bestseller' => true,
                'sales_count' => 45,
                'published_at' => now()->subDays(15),
            ],
            [
                'name' => 'طاولة قهوة خشبية',
                'brand' => 'Premium Wood',
                'collection' => 'Natural Series',
                'description' => 'طاولة قهوة خشبية عالية الجودة',
                'price' => 349.00,
                'discount' => 10,
                'image' => '/images/sofa3.png',
                'images' => ['/images/sofa3.png', '/images/sofa.png'],
                'rating' => 4,
                'tab' => 'new',
                'category_id' => $categories->where('name', 'طاولات')->first()->id,
                'colors' => ['#8B4513', '#654321'],
                'status' => 'active',
                'stock' => 25,
                'sku' => 'TABLE-COFFEE',
                'featured' => false,
                'is_offer' => false,
                'is_bestseller' => false,
                'sales_count' => 8,
                'published_at' => now()->subDays(2),
            ],
            [
                'name' => 'ستائر بليت أنيقة',
                'brand' => 'Somfy',
                'collection' => 'Elegant Series',
                'description' => 'ستائر بليت بتصميم أنيق وعصري',
                'price' => 650.00,
                'discount' => 20,
                'image' => '/images/curtain1.png',
                'images' => ['/images/curtain1.png', '/images/curtain.png'],
                'rating' => 4,
                'tab' => 'offers',
                'category_id' => $categories->where('name', 'ستائر قماشية')->first()->id,
                'colors' => ['#808080', '#A9A9A9', '#696969'],
                'status' => 'active',
                'stock' => 40,
                'sku' => 'BLIND-ELEGANT',
                'featured' => false,
                'is_offer' => true,
                'is_bestseller' => false,
                'sales_count' => 12,
                'published_at' => now()->subDays(10),
            ],
            [
                'name' => 'ستائر رومانية فاخرة',
                'brand' => 'Luxury Curtains',
                'collection' => 'Royal Series',
                'description' => 'ستائر رومانية فاخرة بتصميم كلاسيكي',
                'price' => 950.00,
                'discount' => 30,
                'image' => '/images/curtain.png',
                'images' => ['/images/curtain.png', '/images/curtain1.png'],
                'rating' => 5,
                'tab' => 'featured',
                'category_id' => $categories->where('name', 'ستائر قماشية')->first()->id,
                'colors' => ['#8B0000', '#006400', '#4B0082'],
                'status' => 'active',
                'stock' => 35,
                'sku' => 'ROMAN-LUXURY',
                'featured' => true,
                'is_offer' => true,
                'is_bestseller' => true,
                'sales_count' => 38,
                'published_at' => now()->subDays(8),
            ],
            [
                'name' => 'كنبة أنيقة 2 مقعد',
                'brand' => 'Elegant Home',
                'collection' => 'Comfort Series',
                'description' => 'كنبة أنيقة ومريحة للجلوس',
                'price' => 899.00,
                'discount' => 15,
                'image' => '/images/sofa3.png',
                'images' => ['/images/sofa3.png', '/images/sofa.png'],
                'rating' => 4,
                'tab' => 'bestsellers',
                'category_id' => $categories->where('name', 'كنب وأرائك')->first()->id,
                'colors' => ['#2F4F4F', '#696969', '#708090'],
                'status' => 'active',
                'stock' => 20,
                'sku' => 'SOFA-2S',
                'featured' => true,
                'is_offer' => false,
                'is_bestseller' => true,
                'sales_count' => 42,
                'published_at' => now()->subDays(12),
            ],
            [
                'name' => 'طاولة طعام خشبية',
                'brand' => 'Natural Wood',
                'collection' => 'Family Series',
                'description' => 'طاولة طعام خشبية عائلية',
                'price' => 599.00,
                'discount' => 20,
                'image' => '/images/sofa3.png',
                'images' => ['/images/sofa3.png', '/images/sofa.png'],
                'rating' => 4,
                'tab' => 'featured',
                'category_id' => $categories->where('name', 'طاولات')->first()->id,
                'colors' => ['#8B4513', '#654321'],
                'status' => 'active',
                'stock' => 15,
                'sku' => 'TABLE-DINING',
                'featured' => true,
                'is_offer' => true,
                'is_bestseller' => false,
                'sales_count' => 18,
                'published_at' => now()->subDays(6),
            ],
            [
                'name' => 'ستائر شفافة كلاسيكية',
                'brand' => 'Sheer Elegance',
                'collection' => 'Light Series',
                'description' => 'ستائر شفافة أنيقة للديكور',
                'price' => 450.00,
                'discount' => 25,
                'image' => '/images/curtain1.png',
                'images' => ['/images/curtain1.png', '/images/curtain.png'],
                'rating' => 4,
                'tab' => 'new',
                'category_id' => $categories->where('name', 'ستائر قماشية')->first()->id,
                'colors' => ['#F5F5DC', '#F0F8FF', '#FFF8DC'],
                'status' => 'active',
                'stock' => 60,
                'sku' => 'SHEER-CLASSIC',
                'featured' => true,
                'is_offer' => true,
                'is_bestseller' => false,
                'sales_count' => 22,
                'published_at' => now()->subDays(1),
            ],
            [
                'name' => 'كرسي مكتب فاخر',
                'brand' => 'Office Comfort',
                'collection' => 'Professional Series',
                'description' => 'كرسي مكتب مريح وفاخر',
                'price' => 299.00,
                'discount' => 10,
                'image' => '/images/sofa3.png',
                'images' => ['/images/sofa3.png', '/images/sofa.png'],
                'rating' => 5,
                'tab' => 'bestsellers',
                'category_id' => $categories->where('name', 'كنب وأرائك')->first()->id,
                'colors' => ['#000000', '#2F4F4F', '#696969'],
                'status' => 'active',
                'stock' => 25,
                'sku' => 'CHAIR-OFFICE',
                'featured' => true,
                'is_offer' => false,
                'is_bestseller' => true,
                'sales_count' => 35,
                'published_at' => now()->subDays(20),
            ],
            [
                'name' => 'طاولة جانبية أنيقة',
                'brand' => 'Side Elegance',
                'collection' => 'Accent Series',
                'description' => 'طاولة جانبية أنيقة للديكور',
                'price' => 199.00,
                'discount' => 15,
                'image' => '/images/sofa3.png',
                'images' => ['/images/sofa3.png', '/images/sofa.png'],
                'rating' => 4,
                'tab' => 'offers',
                'category_id' => $categories->where('name', 'طاولات')->first()->id,
                'colors' => ['#8B4513', '#654321'],
                'status' => 'active',
                'stock' => 30,
                'sku' => 'TABLE-SIDE',
                'featured' => true,
                'is_offer' => true,
                'is_bestseller' => false,
                'sales_count' => 28,
                'published_at' => now()->subDays(7),
            ],
        ];

        foreach ($products as $productData) {
            Product::firstOrCreate(
                ['sku' => $productData['sku']],
                $productData
            );
        }
    }
}
