import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { FaFacebookF, FaTwitter, FaInstagram, FaLinkedinIn } from 'react-icons/fa';
const CoverSection = ({ imageUrl = '', title = '', subtitle = '', description = '', socialLinks = {
    facebook: '#',
    twitter: '#',
    instagram: '#',
    linkedin: '#',
}, }) => {
    return (_jsx("div", { className: "relative w-full h-64 md:h-72 lg:h-80 overflow-hidden", children: _jsx("div", { className: "absolute inset-0 bg-cover bg-center", style: { backgroundImage: `url(${imageUrl})` }, children: _jsx("div", { className: "absolute inset-0 flex items-center justify-center", style: { backgroundColor: 'rgba(4, 21, 28, 0.5)' }, children: _jsxs("div", { className: "w-full text-white px-4 sm:px-6 lg:px-8 flex justify-between items-end", children: [_jsxs("div", { className: "max-w-2xl", children: [_jsx("h1", { className: "text-xl sm:text-2xl md:text-3xl lg:text-4xl xl:text-5xl font-bold mb-2 md:mb-4 leading-tight", children: title }), subtitle && (_jsx("p", { className: "text-sm md:text-base lg:text-lg text-gray-200 mb-2", children: subtitle })), description && (_jsx("p", { className: "text-xs md:text-sm lg:text-base text-gray-300 leading-relaxed", children: description }))] }), _jsxs("div", { className: "flex flex-col justify-end items-center gap-3 md:gap-4", children: [_jsx("span", { className: "font-bold text-sm md:text-base", children: "\u0634\u0627\u0631\u0643" }), _jsxs("div", { className: "flex space-x-3 md:space-x-4 rtl:space-x-reverse", children: [_jsx("a", { href: socialLinks.linkedin, target: "_blank", rel: "noopener noreferrer", className: "transition-all hover:text-yellow-400", children: _jsx(FaLinkedinIn, { className: "w-4 h-4 md:w-5 md:h-5" }) }), _jsx("a", { href: socialLinks.instagram, target: "_blank", rel: "noopener noreferrer", className: "transition-all hover:text-yellow-400", children: _jsx(FaInstagram, { className: "w-4 h-4 md:w-5 md:h-5" }) }), _jsx("a", { href: socialLinks.twitter, target: "_blank", rel: "noopener noreferrer", className: "transition-all hover:text-yellow-400", children: _jsx(FaTwitter, { className: "w-4 h-4 md:w-5 md:h-5" }) }), _jsx("a", { href: socialLinks.facebook, target: "_blank", rel: "noopener noreferrer", className: "transition-all hover:text-yellow-400", children: _jsx(FaFacebookF, { className: "w-4 h-4 md:w-5 md:h-5" }) })] })] })] }) }) }) }));
};
export default CoverSection;
