import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { Link, usePage } from '@inertiajs/react';
import { Head } from '@inertiajs/react';
import { FaHome, FaUsers, FaBriefcase, FaEnvelope, FaCog, FaSignOutAlt, FaBars, FaTimes, FaUser, FaTools, FaNewspaper } from 'react-icons/fa';
const AdminLayout = ({ children, title = 'لوحة التحكم', user }) => {
    const { auth, user: pageUser } = usePage().props;
    const currentUser = user || pageUser || auth.user;
    const [sidebarOpen, setSidebarOpen] = useState(false);
    const menuItems = [
        { name: 'الرئيسية', icon: FaHome, href: '/dashboard', active: route().current('admin.dashboard') },
        { name: 'المنتجات', icon: FaBriefcase, href: '/admin/products', active: route().current('admin.products.*') },
        { name: 'الفئات', icon: FaUsers, href: '/admin/categories', active: route().current('admin.categories.*') },
        { name: 'المقالات', icon: FaNewspaper, href: '/admin/articles', active: route().current('admin.articles.*') },
        { name: 'أدوات وإرشادات', icon: FaTools, href: '/admin/tools', active: route().current('admin.tools.*') },
        { name: 'الوظائف', icon: FaBriefcase, href: '/admin/jobs', active: route().current('admin.jobs.*') },
        { name: 'التقديمات', icon: FaUsers, href: '/admin/applications', active: route().current('admin.applications.*') },
        { name: 'الرسائل', icon: FaEnvelope, href: '/admin/contacts', active: route().current('admin.contacts.*') },
        { name: 'الإعدادات', icon: FaCog, href: '/admin/settings', active: route().current('admin.settings.*') },
    ];
    return (_jsxs("div", { className: "min-h-screen bg-gray-50 flex", children: [_jsx(Head, { title: title }), _jsx("div", { className: `h-screen fixed inset-y-0 right-0 z-50 w-64 bg-white shadow-lg transform transition-transform duration-300 ease-in-out lg:translate-x-0 ${sidebarOpen ? 'translate-x-0' : 'translate-x-full lg:translate-x-0'}`, children: _jsxs("div", { className: "flex flex-col h-full", children: [_jsxs("div", { className: "flex items-center justify-center p-6 border-b border-gray-200", children: [_jsx(Link, { href: "/", className: "flex items-center justify-center space-x-3 rtl:space-x-reverse", children: _jsx("img", { src: "/images/logo.png", alt: "\u0625\u064A\u0641\u064A\u0627", className: "h-10 w-auto object-contain" }) }), _jsx("button", { onClick: () => setSidebarOpen(false), className: "lg:hidden p-2 rounded-md text-gray-400 hover:text-gray-600 hover:bg-gray-100", title: "\u0625\u063A\u0644\u0627\u0642 \u0627\u0644\u0642\u0627\u0626\u0645\u0629", children: _jsx(FaTimes, { className: "w-5 h-5" }) })] }), _jsx("nav", { className: "flex-1 px-4 py-6 space-y-2 overflow-y-auto", children: menuItems.map((item) => {
                                const Icon = item.icon;
                                return (_jsxs(Link, { href: item.href, className: `flex items-center space-x-3 rtl:space-x-reverse px-4 py-3 rounded-lg text-sm font-medium transition-all duration-200 ${item.active
                                        ? 'bg-primary-yellow text-primary-black shadow-md'
                                        : 'text-gray-600 hover:bg-gray-100 hover:text-gray-900'}`, children: [_jsx(Icon, { className: "w-5 h-5" }), _jsx("span", { children: item.name })] }, item.name));
                            }) }), _jsxs("div", { className: "p-4 border-t border-gray-200 bg-white", children: [_jsxs("div", { className: "flex items-center space-x-3 rtl:space-x-reverse", children: [_jsx("div", { className: "w-10 h-10 bg-primary-yellow rounded-full flex items-center justify-center", children: _jsx(FaUser, { className: "w-5 h-5 text-primary-black" }) }), _jsxs("div", { className: "flex-1 min-w-0", children: [_jsx("p", { className: "text-sm font-medium text-gray-900 truncate", children: currentUser.name }), _jsx("p", { className: "text-xs text-gray-500 truncate", children: currentUser.email })] })] }), _jsxs(Link, { href: route('logout'), method: "post", as: "button", className: "mt-3 w-full flex items-center space-x-3 rtl:space-x-reverse px-4 py-2 text-sm font-medium text-red-600 hover:bg-red-50 rounded-lg transition-colors duration-200", children: [_jsx(FaSignOutAlt, { className: "w-4 h-4" }), _jsx("span", { children: "\u062A\u0633\u062C\u064A\u0644 \u0627\u0644\u062E\u0631\u0648\u062C" })] })] })] }) }), _jsxs("div", { className: "flex-1 flex flex-col lg:mr-64", children: [_jsx("header", { className: "bg-white shadow-sm border-b border-gray-200 sticky top-0 z-40", children: _jsxs("div", { className: "flex items-center justify-between px-6 py-4", children: [_jsxs("div", { className: "flex items-center space-x-4 rtl:space-x-reverse", children: [_jsx("button", { onClick: () => setSidebarOpen(true), className: "lg:hidden p-2 rounded-md text-gray-400 hover:text-gray-600 hover:bg-gray-100", title: "\u0641\u062A\u062D \u0627\u0644\u0642\u0627\u0626\u0645\u0629", children: _jsx(FaBars, { className: "w-5 h-5" }) }), _jsx("h1", { className: "text-2xl font-bold text-gray-900", children: title })] }), _jsx("div", { className: "flex items-center space-x-4 rtl:space-x-reverse", children: _jsx(Link, { href: "/", className: "text-sm text-gray-600 hover:text-gray-900 transition-colors duration-200", children: "\u0627\u0644\u0639\u0648\u062F\u0629 \u0644\u0644\u0645\u0648\u0642\u0639" }) })] }) }), _jsx("main", { className: "flex-1 p-6 overflow-y-auto", children: children })] }), sidebarOpen && (_jsx("div", { className: "fixed inset-0 z-40 bg-black bg-opacity-50 lg:hidden", onClick: () => setSidebarOpen(false) }))] }));
};
export default AdminLayout;
