import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import ApplicationLogo from '@/Components/ApplicationLogo';
import Dropdown from '@/Components/Dropdown';
import NavLink from '@/Components/NavLink';
import ResponsiveNavLink from '@/Components/ResponsiveNavLink';
import { Link, usePage } from '@inertiajs/react';
import { useState } from 'react';
export default function Authenticated({ header, children, }) {
    const user = usePage().props.auth?.user;
    const [showingNavigationDropdown, setShowingNavigationDropdown] = useState(false);
    if (!user) {
        return null;
    }
    return (_jsxs("div", { className: "min-h-screen bg-gray-100", children: [_jsxs("nav", { className: "border-b border-gray-100 bg-white", children: [_jsx("div", { className: "mx-auto max-w-7xl px-4 sm:px-6 lg:px-8", children: _jsxs("div", { className: "flex h-16 justify-between", children: [_jsxs("div", { className: "flex", children: [_jsx("div", { className: "flex shrink-0 items-center", children: _jsx(Link, { href: "/", children: _jsx(ApplicationLogo, { className: "block h-9 w-auto fill-current text-gray-800" }) }) }), _jsx("div", { className: "hidden space-x-8 sm:-my-px sm:ms-10 sm:flex", children: _jsx(NavLink, { href: route('dashboard'), active: route().current('dashboard'), children: "Dashboard" }) })] }), _jsx("div", { className: "hidden sm:ms-6 sm:flex sm:items-center", children: _jsx("div", { className: "relative ms-3", children: _jsxs(Dropdown, { children: [_jsx(Dropdown.Trigger, { children: _jsx("span", { className: "inline-flex rounded-md", children: _jsxs("button", { type: "button", className: "inline-flex items-center rounded-md border border-transparent bg-white px-3 py-2 text-sm font-medium leading-4 text-gray-500 transition duration-150 ease-in-out hover:text-gray-700 focus:outline-none", children: [user.name, _jsx("svg", { className: "-me-0.5 ms-2 h-4 w-4", xmlns: "http://www.w3.org/2000/svg", viewBox: "0 0 20 20", fill: "currentColor", children: _jsx("path", { fillRule: "evenodd", d: "M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z", clipRule: "evenodd" }) })] }) }) }), _jsxs(Dropdown.Content, { children: [_jsx(Dropdown.Link, { href: route('profile.edit'), children: "Profile" }), _jsx(Dropdown.Link, { href: route('logout'), method: "post", as: "button", children: "Log Out" })] })] }) }) }), _jsx("div", { className: "-me-2 flex items-center sm:hidden", children: _jsx("button", { title: "Showing Navigation Dropdown", type: "button", onClick: () => setShowingNavigationDropdown((previousState) => !previousState), className: "inline-flex items-center justify-center rounded-md p-2 text-gray-400 transition duration-150 ease-in-out hover:bg-gray-100 hover:text-gray-500 focus:bg-gray-100 focus:text-gray-500 focus:outline-none", children: _jsxs("svg", { className: "h-6 w-6", stroke: "currentColor", fill: "none", viewBox: "0 0 24 24", children: [_jsx("path", { className: !showingNavigationDropdown
                                                        ? 'inline-flex'
                                                        : 'hidden', strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: "2", d: "M4 6h16M4 12h16M4 18h16" }), _jsx("path", { className: showingNavigationDropdown
                                                        ? 'inline-flex'
                                                        : 'hidden', strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: "2", d: "M6 18L18 6M6 6l12 12" })] }) }) })] }) }), _jsxs("div", { className: (showingNavigationDropdown ? 'block' : 'hidden') +
                            ' sm:hidden', children: [_jsx("div", { className: "space-y-1 pb-3 pt-2", children: _jsx(ResponsiveNavLink, { href: route('dashboard'), active: route().current('dashboard'), children: "Dashboard" }) }), _jsxs("div", { className: "border-t border-gray-200 pb-1 pt-4", children: [_jsxs("div", { className: "px-4", children: [_jsx("div", { className: "text-base font-medium text-gray-800", children: user.name }), _jsx("div", { className: "text-sm font-medium text-gray-500", children: user.email })] }), _jsxs("div", { className: "mt-3 space-y-1", children: [_jsx(ResponsiveNavLink, { href: route('profile.edit'), children: "Profile" }), _jsx(ResponsiveNavLink, { method: "post", href: route('logout'), as: "button", children: "Log Out" })] })] })] })] }), header && (_jsx("header", { className: "bg-white shadow", children: _jsx("div", { className: "mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8", children: header }) })), _jsx("main", { children: children })] }));
}
